import math
import os
import json

import numpy as np
import torch
from tqdm import tqdm

from exp.exp_basic import Exp_Basic
from utils.loss import L2Loss


GEOMETRIC_TARGET_DIM = 9


class Exp_VascularPretrain(Exp_Basic):
    """Lifted geometric pre-training for vascular STL-derived samples."""

    @property
    def geom_target_dim(self):
        if hasattr(self, "_geom_target_dim"):
            return self._geom_target_dim
        walk_steps = getattr(getattr(self, "args", None), "walk_steps", 3)
        return 3 * int(walk_steps)

    @geom_target_dim.setter
    def geom_target_dim(self, value):
        self._geom_target_dim = value

    def __init__(self, args):
        super().__init__(args)
        self.walk_steps = getattr(self.args, "walk_steps", 3)
        self.geom_target_dim = 3 * self.walk_steps
        self.analytic_flow_dict = (
            getattr(self.args, "vascular_physics_proxy_mode", "")
            == "learnable_generalized_flow_compact"
        )
        if self.analytic_flow_dict:
            from models.dynamic_flow_dict import AnalyticCompactFlowDictionary
            self.flow_dict = AnalyticCompactFlowDictionary(
                morph_dim=7,
                cond_dim=4,
                num_modes=8,
                loss_weight_noslip=getattr(self.args, "dict_loss_weight_noslip", 0.1),
                loss_weight_div=getattr(self.args, "dict_loss_weight_div", 0.05),
                loss_weight_entropy=getattr(self.args, "dict_loss_weight_entropy", 0.01),
                rw_encoder_hidden_dim=getattr(self.args, "rw_encoder_hidden_dim", 16),
                rw_feature_dim=getattr(self.args, "rw_encoder_feature_dim", 16),
                rw_encoder_num_steps=self.walk_steps,
            ).to(self.device)
            print(
                "Initialized fixed 8-mode analytic dictionary with learnable 8-way routing gate.",
                flush=True,
            )
        elif getattr(self.args, "vascular_physics_proxy_mode", "") == "learnable_dynamic_flow_dict":
            from models.dynamic_flow_dict import NeuralFlowDictionary
            self.flow_dict = NeuralFlowDictionary(
                morph_dim=7,
                cond_dim=4,
                num_modes=getattr(self.args, "dict_num_modes", 4),
                loss_weight_noslip=getattr(self.args, "dict_loss_weight_noslip", 0.1),
                loss_weight_div=getattr(self.args, "dict_loss_weight_div", 0.05),
                loss_weight_ortho=getattr(self.args, "dict_loss_weight_ortho", 0.05),
                loss_weight_energy=getattr(self.args, "dict_loss_weight_energy", 0.1),
                loss_weight_entropy=getattr(self.args, "dict_loss_weight_entropy", 0.01),
                rw_encoder_hidden_dim=getattr(self.args, "rw_encoder_hidden_dim", 16),
                rw_feature_dim=getattr(self.args, "rw_encoder_feature_dim", 16),
                rw_encoder_num_steps=self.walk_steps,
            ).to(self.device)
            print(f"Initialized Self-Supervised NeuralFlowDictionary with {getattr(self.args, 'dict_num_modes', 4)} modes (kinetic energy constrained, MLS divergence).", flush=True)
        else:
            self.flow_dict = None

    def _prepare_dynamic_targets(
        self, pos, fx, unmasked_geom, y, analytic_basis=None, training=False
    ):
        """
        If using learnable_dynamic_flow_dict:
          1. Generate dynamic flow proxy targets using the neural dictionary.
          2. DETACH the generated proxy target before supervising Transolver to prevent
             zero-flow trivial collapse.
          3. Compute self-supervised physics losses (no-slip, MLS divergence, energy, orthogonality)
             using CLEAN unmasked wall distances.
        """
        if self.flow_dict is None:
            return y, 0.0, None

        pos_xyz = pos[:, :, :3]
        # fx has [geom_masked (4), probe_cond (4)]
        # For dictionary input, use unmasked geometry features [pos, unmasked_geom]
        morph = torch.cat([pos_xyz, unmasked_geom[:, :, :4]], dim=-1)
        cond = fx[:, :, 4:8]
        # The first nine target channels are the three-step wall-displacement
        # trajectory generated by the random-walk probe.  It is geometry-only
        # self-supervision, not CFD velocity/pressure ground truth, and is fed
        # through the small RW encoder used by the routing gate.
        rw_trajectory = y[:, :, :self.geom_target_dim]
        if self.analytic_flow_dict:
            if analytic_basis is None:
                raise RuntimeError(
                    "learnable_generalized_flow_compact requires an analytic (B,N,8,3) flow bank"
                )
            dynamic_proxy, basis, weights = self.flow_dict(
                pos_xyz, morph, cond, analytic_basis,
                rw_trajectory=rw_trajectory,
            )
        else:
            dynamic_proxy, basis, weights = self.flow_dict(
                pos_xyz, morph, cond, rw_trajectory=rw_trajectory
            )

        # DETACH dynamic proxy to prevent Transolver prediction loss from pushing generator to 0
        y_dynamic = torch.cat([y[:, :, :self.geom_target_dim], dynamic_proxy.detach()], dim=-1)

        dict_losses = None
        dict_loss_val = 0.0
        if training:
            # Use clean, unmasked wall distance for true no-slip boundary condition
            true_wall_dist = unmasked_geom[:, :, :1]
            dict_losses = self.flow_dict.compute_self_supervised_losses(pos_xyz, basis, weights, true_wall_dist)
            dict_loss_val = dict_losses["loss_dict_total"]

        return y_dynamic, dict_loss_val, dict_losses

    def _use_physics_proxy_loss(self, out, y):
        return (
            getattr(self.args, "vascular_physics_proxy", False)
            and out.shape[-1] > self.geom_target_dim
            and y.shape[-1] > self.geom_target_dim
        )

    def _loss_components(self, out, y, myloss, dict_loss_val=0.0):
        if self._use_physics_proxy_loss(out, y):
            geom_loss = myloss(out[:, :, :self.geom_target_dim].contiguous(),
                               y[:, :, :self.geom_target_dim].contiguous())
            phys_loss = myloss(out[:, :, self.geom_target_dim:].contiguous(),
                               y[:, :, self.geom_target_dim:].contiguous())
            phys_weight = getattr(self.args, "vascular_physics_weight", 0.25)
            # L2Loss(size_average=False) returns a batch sum, while the
            # dictionary self-supervision is reduced as a batch mean. Convert
            # the dictionary term to the same batch-sum scale before joining it
            # to the flow branch. This keeps its effective weight independent
            # of batch size and makes the loss hierarchy explicit:
            #   flow_loss = compact_prediction_loss + dictionary_loss
            if torch.is_tensor(dict_loss_val):
                dict_loss_batch = dict_loss_val * out.shape[0]
            else:
                dict_loss_batch = torch.as_tensor(
                    dict_loss_val, device=out.device, dtype=out.dtype
                ) * out.shape[0]
            flow_loss = phys_loss + dict_loss_batch
            total_loss = geom_loss + phys_weight * flow_loss
            return total_loss, geom_loss, phys_loss

        loss = myloss(out, y)
        return loss, loss, None

    def vali(self, epoch=None):
        myloss = L2Loss(size_average=False)
        self.model.eval()
        if self.flow_dict is not None:
            self.flow_dict.eval()
        rel_err = 0.0
        geom_err = 0.0
        phys_err = 0.0
        phys_batches = 0
        n = 0
        desc = "Val"
        if epoch is not None:
            desc = f"Epoch {epoch + 1}/{self.args.epochs} val"
        with torch.no_grad():
            pbar = tqdm(self.test_loader, desc=desc, total=len(self.test_loader),
                        dynamic_ncols=True, mininterval=2.0)
            for batch in pbar:
                pos, fx, unmasked_geom, y = batch[:4]
                analytic_basis = batch[4] if len(batch) > 4 else None
                pos = pos.to(self.device)
                fx = fx.to(self.device)
                unmasked_geom = unmasked_geom.to(self.device)
                y = y.to(self.device)
                if analytic_basis is not None:
                    analytic_basis = analytic_basis.to(self.device)
                y, _, _ = self._prepare_dynamic_targets(
                    pos, fx, unmasked_geom, y,
                    analytic_basis=analytic_basis,
                    training=False,
                )
                out = self.model(pos[:, :, :3], fx)
                loss, geom_loss, phys_loss = self._loss_components(out, y, myloss)
                # Dynamic dictionary targets move during training; select checkpoints
                # using the fixed geometric target so validation remains comparable.
                rel_err += (geom_loss if self.flow_dict is not None else loss).item()
                geom_err += geom_loss.item()
                if phys_loss is not None:
                    phys_err += phys_loss.item()
                    phys_batches += pos.shape[0]
                n += pos.shape[0]
                postfix = {"rel_l2": rel_err / max(n, 1)}
                if phys_loss is not None:
                    postfix["geom_l2"] = geom_err / max(n, 1)
                    postfix["phys_l2"] = phys_err / max(phys_batches, 1)
                pbar.set_postfix(**postfix)
        return rel_err / max(n, 1)

    def train(self):
        trainable_params = list(self.model.parameters())
        if self.flow_dict is not None:
            trainable_params += list(self.flow_dict.parameters())

        if self.args.optimizer == 'AdamW':
            optimizer = torch.optim.AdamW(trainable_params, lr=self.args.lr, weight_decay=self.args.weight_decay)
        elif self.args.optimizer == 'Adam':
            optimizer = torch.optim.Adam(trainable_params, lr=self.args.lr, weight_decay=self.args.weight_decay)
        else:
            raise ValueError('Optimizer only AdamW or Adam')

        if self.args.scheduler == 'OneCycleLR':
            scheduler = torch.optim.lr_scheduler.OneCycleLR(
                optimizer, max_lr=self.args.lr, epochs=self.args.epochs,
                steps_per_epoch=len(self.train_loader), pct_start=self.args.pct_start)
        elif self.args.scheduler == 'CosineAnnealingLR':
            warmup_epochs = getattr(self.args, 'warmup_epochs', 0)
            if warmup_epochs > 0:
                def lr_lambda(epoch):
                    if epoch < warmup_epochs:
                        return float(epoch + 1) / float(max(1, warmup_epochs))
                    progress = float(epoch - warmup_epochs) / float(max(1, self.args.epochs - warmup_epochs))
                    return 0.5 * (1.0 + math.cos(math.pi * min(1.0, progress)))

                scheduler = torch.optim.lr_scheduler.LambdaLR(optimizer, lr_lambda)
            else:
                scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=self.args.epochs)
        elif self.args.scheduler == 'StepLR':
            scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=self.args.step_size, gamma=self.args.gamma)
        else:
            scheduler = None

        myloss = L2Loss(size_average=False)
        train_loss_list = []
        test_loss_list = []
        routing_history = []
        best_val = float("inf")
        best_epoch = -1
        bad_epochs = 0
        checkpoint_interval = max(0, int(getattr(self.args, "checkpoint_interval", 0)))

        for ep in range(self.args.epochs):
            self.model.train()
            if self.flow_dict is not None:
                self.flow_dict.train()
            train_loss = 0.0
            train_geom_loss = 0.0
            train_phys_loss = 0.0
            train_dict_loss = 0.0
            train_basis_norm = 0.0
            train_proxy_speed = 0.0
            train_gate_entropy = 0.0
            train_mode_weight_mean = None
            train_mode_weight_std = None
            train_phys_batches = 0
            n = 0
            lr = optimizer.param_groups[0]['lr']
            pbar = tqdm(self.train_loader,
                        desc=f"Epoch {ep + 1}/{self.args.epochs} train",
                        total=len(self.train_loader),
                        dynamic_ncols=True,
                        mininterval=2.0)
            for batch in pbar:
                pos, fx, unmasked_geom, y = batch[:4]
                analytic_basis = batch[4] if len(batch) > 4 else None
                pos = pos.to(self.device)
                fx = fx.to(self.device)
                unmasked_geom = unmasked_geom.to(self.device)
                y = y.to(self.device)
                if analytic_basis is not None:
                    analytic_basis = analytic_basis.to(self.device)

                y, dict_loss_val, dict_losses = self._prepare_dynamic_targets(
                    pos, fx, unmasked_geom, y,
                    analytic_basis=analytic_basis,
                    training=True,
                )
                out = self.model(pos[:, :, :3], fx)
                loss, geom_loss, phys_loss = self._loss_components(
                    out, y, myloss, dict_loss_val=dict_loss_val
                )
                if self.flow_dict is not None and isinstance(dict_loss_val, torch.Tensor):
                    train_dict_loss += dict_loss_val.item() * pos.shape[0]
                    if dict_losses is not None:
                        train_basis_norm += dict_losses.get("basis_norm", torch.tensor(0.0)).item() * pos.shape[0]
                        train_proxy_speed += dict_losses.get("proxy_speed", torch.tensor(0.0)).item() * pos.shape[0]
                        train_gate_entropy += dict_losses.get("gate_entropy", torch.tensor(0.0)).item() * pos.shape[0]
                        mode_mean = dict_losses.get("mode_weight_mean")
                        mode_std = dict_losses.get("mode_weight_std")
                        if mode_mean is not None:
                            mode_mean = mode_mean.detach().cpu()
                            train_mode_weight_mean = (
                                mode_mean * pos.shape[0]
                                if train_mode_weight_mean is None
                                else train_mode_weight_mean + mode_mean * pos.shape[0]
                            )
                        if mode_std is not None:
                            mode_std = mode_std.detach().cpu()
                            train_mode_weight_std = (
                                mode_std * pos.shape[0]
                                if train_mode_weight_std is None
                                else train_mode_weight_std + mode_std * pos.shape[0]
                            )

                optimizer.zero_grad()
                loss.backward()
                if self.args.max_grad_norm is not None:
                    torch.nn.utils.clip_grad_norm_(trainable_params, self.args.max_grad_norm)
                optimizer.step()
                if self.args.scheduler == 'OneCycleLR' and scheduler is not None:
                    scheduler.step()

                train_loss += loss.item()
                train_geom_loss += geom_loss.item()
                if phys_loss is not None:
                    train_phys_loss += phys_loss.item()
                    train_phys_batches += pos.shape[0]
                n += pos.shape[0]
                postfix = {"loss": train_loss / max(n, 1), "lr": lr}
                if phys_loss is not None:
                    postfix["geom_l2"] = train_geom_loss / max(n, 1)
                    postfix["phys_l2"] = train_phys_loss / max(train_phys_batches, 1)
                if self.flow_dict is not None:
                    postfix["dict_l"] = train_dict_loss / max(n, 1)
                    postfix["b_norm"] = train_basis_norm / max(n, 1)
                    postfix["p_spd"] = train_proxy_speed / max(n, 1)
                pbar.set_postfix(**postfix)

            if self.args.scheduler in ('CosineAnnealingLR', 'StepLR') and scheduler is not None:
                scheduler.step()

            train_loss = train_loss / max(n, 1)
            rel_err = self.vali(epoch=ep)
            train_loss_list.append(train_loss)
            test_loss_list.append(rel_err)
            print(f"Epoch {ep + 1}/{self.args.epochs} Train loss: {train_loss:.5f} lr: {optimizer.param_groups[0]['lr']:.6g}", flush=True)
            improved = rel_err < best_val - getattr(self.args, "min_delta", 0.0)
            if improved:
                best_val = rel_err
                best_epoch = ep
                bad_epochs = 0
                self._save_model(ep, best_val, optimizer, scheduler)
            else:
                bad_epochs += 1
            print(f"Epoch {ep + 1}/{self.args.epochs} val rel_err: {rel_err} "
                  f"best={best_val}@{best_epoch + 1} bad_epochs={bad_epochs}", flush=True)
            if self.flow_dict is not None:
                gate_entropy = train_gate_entropy / max(n, 1)
                if train_mode_weight_mean is not None:
                    mode_mean = train_mode_weight_mean / max(n, 1)
                    mode_text = ",".join(f"{v:.3f}" for v in mode_mean.tolist())
                else:
                    mode_mean = None
                    mode_text = ""
                if train_mode_weight_std is not None:
                    mode_std = train_mode_weight_std / max(n, 1)
                    mode_std_text = ",".join(f"{v:.3f}" for v in mode_std.tolist())
                else:
                    mode_std = None
                    mode_std_text = ""
                print(
                    f"Epoch {ep + 1}/{self.args.epochs} dict gate_entropy={gate_entropy:.5f} "
                    f"mode_mean=[{mode_text}] mode_std=[{mode_std_text}]",
                    flush=True,
                )
                routing_history.append({
                    "epoch": ep + 1,
                    "gate_entropy": gate_entropy,
                    "mode_weight_mean": mode_mean.tolist() if mode_mean is not None else [],
                    "mode_weight_std": mode_std.tolist() if mode_std is not None else [],
                })

            if ep % 10 == 0:
                self._save_logs(train_loss_list, test_loss_list, routing_history)
            if checkpoint_interval > 0 and (ep + 1) % checkpoint_interval == 0:
                self._save_epoch_model(ep + 1, best_val, optimizer, scheduler)
            if self.args.early_stop and bad_epochs >= self.args.patience:
                print(f"[EarlyStop] no improvement for {bad_epochs} epochs; "
                      f"best val rel_err={best_val} at epoch {best_epoch + 1}", flush=True)
                break

        self._save_last_model(ep, best_val, optimizer, scheduler)
        self._save_logs(train_loss_list, test_loss_list, routing_history)

    def _pack_checkpoint(self, epoch=0, best_val=None, optimizer=None, scheduler=None):
        ckpt = {
            'model': self.model.state_dict(),
            'flow_dict': self.flow_dict.state_dict() if self.flow_dict is not None else None,
            'epoch': epoch,
            'best_val': best_val,
            'optimizer': optimizer.state_dict() if optimizer is not None else None,
            'scheduler': scheduler.state_dict() if scheduler is not None else None,
            'rng_state': torch.get_rng_state(),
            'cuda_rng_state': torch.cuda.get_rng_state() if torch.cuda.is_available() else None,
        }
        return ckpt

    def _save_model(self, epoch=0, best_val=None, optimizer=None, scheduler=None):
        os.makedirs('./checkpoints', exist_ok=True)
        ckpt = self._pack_checkpoint(epoch, best_val, optimizer, scheduler)
        torch.save(ckpt, os.path.join('./checkpoints', self.args.save_name + '.pt'))
        torch.save(ckpt, os.path.join('./checkpoints', self.args.save_name + '_best.pt'))

    def _save_epoch_model(self, epoch, best_val=None, optimizer=None, scheduler=None):
        os.makedirs('./checkpoints', exist_ok=True)
        ckpt = self._pack_checkpoint(epoch, best_val, optimizer, scheduler)
        torch.save(ckpt, os.path.join('./checkpoints', f"{self.args.save_name}_epoch{epoch:03d}.pt"))

    def _save_last_model(self, epoch=0, best_val=None, optimizer=None, scheduler=None):
        os.makedirs('./checkpoints', exist_ok=True)
        ckpt = self._pack_checkpoint(epoch, best_val, optimizer, scheduler)
        torch.save(ckpt, os.path.join('./checkpoints', self.args.save_name + '_last.pt'))

    def _save_logs(self, train_loss_list, test_loss_list, routing_history=None):
        os.makedirs('./training_logs', exist_ok=True)
        np.save(os.path.join('./training_logs', self.args.save_name + '_train_loss.npy'),
                np.array(train_loss_list))
        np.save(os.path.join('./training_logs', self.args.save_name + '_test_loss.npy'),
                np.array(test_loss_list))
        if routing_history is not None:
            with open(os.path.join('./training_logs', self.args.save_name + '_routing.json'), 'w') as f:
                json.dump(routing_history, f, indent=2)

    def test(self):
        ckpt_path = os.path.join("./checkpoints", self.args.save_name + ".pt")
        checkpoint = torch.load(ckpt_path, map_location=self.device)
        if isinstance(checkpoint, dict) and 'model' in checkpoint:
            self.model.load_state_dict(checkpoint['model'])
            if self.flow_dict is not None and checkpoint.get('flow_dict') is not None:
                self.flow_dict.load_state_dict(checkpoint['flow_dict'])
                print(f"Loaded synchronized flow_dict from {ckpt_path}")
        else:
            self.model.load_state_dict(checkpoint)
        rel_err = self.vali()
        print("test rel_err:{}".format(rel_err))

    def test_full_mesh(self):
        print("test_full_mesh skipped for vascular pre-training.")
